### ISSUE TITLE
Example broken?

### ISSUE THREAD

**Issue by ChrisJamesC** [Sqooba/mobx-react-intl#12]
When running the example on master, the german translation doesn't work. 

Here is what I have in the console: 
![screenshot 2017-10-05 10 29 58](https://user-images.githubusercontent.com/1410314/31217707-35e0120a-a9b8-11e7-8fb8-211f084d731c.png)

Here is the structure of react components: 
![screenshot 2017-10-05 10 31 37](https://user-images.githubusercontent.com/1410314/31217785-75d648ca-a9b8-11e7-8c24-9adc3a210932.png)

with `messages` on the highlighted line being an empty object

Can someone reproduce this issue?

**Comment by tujoworker** [comment]
Same here, but not once I use the latest "1.3.2" version like ```"mobx-react-intl": "^1.3.2",``` - I got this once I run start or build. Maybe something got not committed from a previous version?

**Comment by ChrisJamesC** [comment]
Ok so I think that my `yarn link` played tricks to me. Once I unlink everything it works well.
