### ISSUE TITLE
`yarn start` broken

### ISSUE THREAD

**Issue by ChrisJamesC** [Sqooba/mobx-react-intl#13]
Not sure if it's for all or just on my local setup but I have the following error on `yarn start`: 

```
Christophers-MacBook-Pro:mobx-react-intl christopherchiche$ yarn start
yarn run v1.1.0
$ tsc-watch --onSuccess "rollup -c"
env: node\r: No such file or directory
error Command failed with exit code 127.
```

**Comment by tujoworker** [comment]
No, yarn works just fine here on this package. Maybe reinstall will help?
But I'm curios, how do You setting up things to test this package on a test react app?

I'v done someting like this ```"mobx-react-intl": "Sqooba/mobx-react-intl",``` in the package.json or also the ```/tarball/master``` methode.

**Comment by ChrisJamesC** [comment]
@tujoworker Thanks, that's what I suspected. I must have broken some node link at some point. 

As per testing the package I use `yarn link`.

**Comment by ChrisJamesC** [comment]
It seems to be only me 🙈
