### ISSUE TITLE
Peer Dependencies Warning

### ISSUE THREAD

**Issue by Timopheym** [Sqooba/mobx-react-intl#17]
Why does it needs "react": "^15.6.1" when in dev dependencies it could work with 16?
I think that migration to 16 is very important due 15's license issues.
Thanks!

**Comment by ChrisJamesC** [comment]
Definitely! I'll look into it soon to see if there is any breaking issue, but PRs are welcome if you have time to look into it

**Comment by Shastick** [comment]
Archiving the repo, closing open issues.
