### ISSUE TITLE
Fails on MobX4+

### ISSUE THREAD

**Issue by CWolfs** [Sqooba/mobx-react-intl#19]
It seems MobX4 brought in some breaking changes so this library is no longer compatible with Mobx4 or 5.

**Comment by ChrisJamesC** [comment]
Hi @CWolfs would you mind opening a PR that fixes the issue? I'll look into it in a few days otherwise.

**Comment by CWolfs** [comment]
I might not have the time to work on it but I'll do my best to look at it for a PR in the next week or two. Basically MobX changes how they work with `observable` and use function decorators like this...

```
decorate(Todo, {
    title: observable,
    finished: observable
})
```

instead of 

```
@observable title,
@observable finshed
```

**Comment by dguayrobotiq** [comment]
Any chance this get fix?

**Comment by daniel-moya** [comment]
I get this
`Error: [mobx] The provided value could not be converted into an observable. If you want just create an observable reference to the object use 'observable.box(value)'
`

``` javascript
const LOCALE = "locale";
   5 | 
   6 | export class LocaleStore {
>  7 |     private _locale = observable("");  // the locale value
   8 |     private translations: {[key: string]: {[id: string]: string}}
   9 | 
  10 |     constructor(defaultLocale: string, translations: {[key: string]: {[id: string]: string}}) {
`

**Comment by Shastick** [comment]
Archiving the repo, closing open issues.
