### ISSUE TITLE
Warnings about mobx imports

### ISSUE THREAD

**Issue by ChrisJamesC** [Sqooba/mobx-react-intl#2]
See: https://www.dropbox.com/s/r97szwfnyg9wa0i/Screenshot%202017-07-24%2014.00.19.png?dl=0

**Comment by KevinOrtman** [comment]
I see this as well.  You already have mobx listed as a peer dependency, but it's also listed in your direct dependencies list.  I think simply removing that direct dependency may resolve this issue.

See:  https://github.com/mobxjs/mobx/issues/1082

**Comment by ChrisJamesC** [comment]
Fixed in #4
