### ISSUE TITLE
Default locale

### ISSUE THREAD

**Issue by KevinOrtman** [Sqooba/mobx-react-intl#3]
react-intl sets 'en' as the default locale, could you do the same with MobxIntlProvider and/or make defaultLocale a prop that we could pass to the component?

**Comment by ChrisJamesC** [comment]
Thanks for the suggestion! I'll look into it!

**Comment by mhabegger** [comment]
👍 
It's set to "de" at the moment.
https://github.com/Sqooba/mobx-react-intl/blob/master/src/MobxIntlProvider.tsx#L9
